### ISSUE TITLE
Keeps loading without connecting - wsproxy problem

### ISSUE THREAD

**Issue by alessio-ds** [stuicey/SSHy#33]
getting this error by using wsproxy

```
alessiosca@kali:~/Scrivania/web/default/ssh$ sudo wsproxy -k /home/alessiosca/Scrivania/web/default/ssh/wsproxy/default.key -c /home/alessiosca/Scrivania/web/default/ssh/wsproxy/default.crt
[sudo] password di alessiosca: 
[Status]: Starting wsProxy on port 5999...
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE null:5999
    at listenOnMasterHandle (net.js:1347:16)
    at rr (internal/cluster/child.js:126:12)
    at Worker.send (internal/cluster/child.js:93:7)
    at process.onInternalMessage (internal/cluster/utils.js:45:8)
    at process.emit (events.js:203:15)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Server.WebSocketServer._ultron.on (/usr/local/lib/node_modules/wsproxy/node_modules/ws/lib/WebSocketServer.js:85:46)
    at Server.emit (events.js:198:13)
    at listenOnMasterHandle (net.js:1348:21)
    at rr (internal/cluster/child.js:126:12)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by candlerb** [comment]
That error implies that there is some other program already listening on port 5999 (EADDRINUSE).  Try killing that program first, and then running wsproxy.
