### ISSUE TITLE
Unable to closure-compile or connect

### ISSUE THREAD

**Issue by Rudi9719** [stuicey/SSHy#42]
```
java -jar closure-compiler.jar --js_output_file=js/combinedLibs.comb.js js/defines.js js/src/*.js js/*.js 'wsproxy/.comb.js' 'wsproxy/Client.js'
ERROR - Cannot read file wsproxy/.comb.js: wsproxy/.comb.js

ERROR - Cannot read file wsproxy/Client.js: wsproxy/Client.js

2 error(s), 0 warning(s)
```

NPM Version 6.14.8
Node Version v14.13.0
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-1, mixed mode)

I tried to make the modifications [here](https://github.com/stuicey/SSHy/issues/26) but was still unable to connect. I also tried updating var wsproxyURL to be the webserver's DNS name.

```
combinedLibs.comb.js:372 Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': The index provided (13) is larger than the maximum index (0).
    at SSHyClient.settings.setColorScheme (https://ssh.nightmare.haus/js/combinedLibs.comb.js:372:85)
    at window.onload (https://ssh.nightmare.haus/:44:13)
(index):222 Uncaught DOMException: Failed to construct 'WebSocket': The URL 'ssh.nightmare.haus' is invalid.
    at startSSHy (https://ssh.nightmare.haus/:222:11)
    at HTMLInputElement.onclick (https://ssh.nightmare.haus/:464:92)
```

commands I ran:

```   
   509  8:42    git clone https://github.com/stuicey/SSHy.git   
   510  8:44    cd SSHy/
   511  8:46    git submodule update --init --recursive
   512  8:46    npm i -g wsproxy/
   513  8:46    wsproxy
   514  8:46    bg
   515  8:46    ls wsproxy/
   516  8:46    java -jar closure-compiler.jar --js_output_file=js/combinedLibs.comb.js js/defines.js js/src/*.js js/*.js 'wsproxy/.comb.js' 'wsproxy/Client.js'
```
Note command 516 was typed as `java -jar closure-compiler.jar --js_output_file=js/combinedLibs.comb.js js/defines.js js/src/*.js js/*.js '!**.comb.js' '!**Client.js'` however bash expanded the ! for some reason.

**Comment by Rudi9719** [comment]
Changed the var wsproxyURL to be "wss://ssh.nightmare.haus" and now I get the following
```
combinedLibs.comb.js:372 Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': The index provided (13) is larger than the maximum index (0).
    at SSHyClient.settings.setColorScheme (https://ssh.nightmare.haus/js/combinedLibs.comb.js:372:85)
    at window.onload (https://ssh.nightmare.haus/:44:13)
setColorScheme @ combinedLibs.comb.js:372
window.onload @ (index):44
load (async)
(anonymous) @ (index):40
(index):222 WebSocket connection to 'wss://ssh.nightmare.haus/' failed: Error during WebSocket handshake: Unexpected response code: 200
startSSHy @ (index):222
onclick @ (index):463
(index):285 Uncaught TypeError: term.fit is not a function
    at termInit ((index):285)
    at WebSocket.ws.onclose ((index):257)
```
Seems like it doesn't appreciate the 200 okay that it is sending?
